---
title:
tags:
  - java
  - programming
  - exception
publish: true
date: 2024-10-10
---

## 처리할 수 없는 예외

- 상대 네트워크 서버에 문제가 발생해서 통신이 불가능
- 데이터베이스 서버에 문제가 발생해서 접속 불가

이렇게 시스템 오류 때문에 발생한 예외들은 대부분 예외를 잡아도 해결 할 수 있는 것이 거의 없다. 예외를 잡아서 다시 호출을 시도해도 같은 오류가 반복될 뿐이다.

이런 경우 고객에게는 시스템 문제라는 것을 오류 메시지를 통해 보여주고, 만약 웹이라면 오류 페이지를 보여주면 된다.

그리고 내부 개발자가 문제 상황을 빠르게 인지할 수 있도록 오류에 대한 로그를 남겨두어야 한다.

## 체크 예외의 부담

![[체크예외의_부담.png]]
체크 예외는 개발자가 실수로 놓칠 수 있는 예외들을 컴파일러가 체크해주기 때문에 오래전부터 많이 사용되었다.

그런데 앞서 설명한 것 처럼 처리할 수 없는 예외가 많아지고 또 프로그램이 점점 복잡해지면서 체크 예외를 사용하는 것이 점점 더 부담스러워졌다.

![[체크예외의_부담1.png]]
결과적으로 이런 형태가 될 것이다.

**정리**

지금까지 알아본 체크 예외를 사용할 때 발생하는 문제들은 다음과 같다.

- **처리할 수 없는 예외**: 예외를 잡아서 복구할 수 있는 예외보다 복구할 수 없는 예외가 더 많다.
- **체크 예외의 부담**: 처리할 수 없는 예외는 밖으로 던져야한다. 체크 예외이므로 `throws`에 던질 대상을 일일이 명시해야 한다.

수 많은 라이브러리에서 쏟아지는 모든 예외를 다 다루고 싶지는 않을 것이다. 특히 본인이 해결할 수도 없는 모든 예외를 다 다루고 싶지는 않을 것이다.

본인이 해결할 수 있는 예외만 잡아서 처리하고, 해결할 수 없는 예외는 신경쓰지 않는 것이 더 나은 선택일 수 있다.

## 언체크 예외 사용 시나리오

![[언체크예외_1.png]]

- 이번에는 `Service`에서 호출하는 클래스들이 언체크(런타임) 예외를 전달한다고 가정한다.
- `NetworkException`, `DatabaseException`은 잡아도 복구할 수 없다. 언체크 예외이므로 이런 경우 무시하면 된다.

```java title="언체크 예외를 던지는 예시"
class Service {
	void sendMessage(String data) {
		...
	}
}
```

- 언체크 예외이므로 `throws`를 선언하지 않아도 된다.
- 사용하는 라이브러리가 늘어나서 언체크 예외가 늘어도 본인이 필요한 예외만 잡으면 된다.

```java title="일부 언체크 예외를 잡아서 처리하는 예시"
try {
	...
} catch (xxxException e) {
	...
}
```

- 상대 네트워크 서버나, 데이터베이스 서버에 문제가 발생한 경우 `Service`에서 예외를 잡아도 복구할 수 없다.
- `Service`에서는 본인이 처리할 수 없는 예외들이기 때문에 밖으로 던지는 것이 나은 결정이다.
- 언체크 예외는 잡지 않으면 `throws` 선언이 없어도 자동으로 밖으로 던진다.
- 만약 일부 언체크 예외를 잡아서 처리할 수 있다면 잡아서 처리하면 된다.

## 예외 공통 처리

이렇게 처리할 수 없는 예외들은 중간에 여러곳에서 나누어 처리하기 보다는 예외를 공통으로 처리할 수 있는 곳을 만들어서 한 곳에서 해결하면 된다.

어차피 해결할 수 없는 예외들이기 때문에 이런 경우 고객에게는 현재 시스템에 문제가 있습니다 등 오류 메세지를 보여주고 만약 웹이라면 오류 페이지를 보여주면 된다.

그리고 내부 개발자가 문제 상황을 빠르게 인지할 수 있도록 오류에 대한 로그를 남겨두면 된다. 이런 부분은 공통 처리가 가능하다.

**공통 예외 처리 방법**

```java title="공통 예외 처리 예제"

public class MainV4 {

  public static void main(String[] args) {
    NetworkServiceV4 networkService = new NetworkServiceV4();

    Scanner scanner = new Scanner(System.in);
    while (true) {
      System.out.print("전송할 문자: ");
      String input = scanner.nextLine();
      if (input.equals("exit")) {
        break;
      }

      try {
        networkService.sendMessage(input);
      } catch (Exception e) {
        exceptionHandler(e);
      }
    }
    System.out.println("프로그램을 정상 종료합니다.");
  }

  // 공통 예외 처리
  private static void exceptionHandler(Exception e) {
    System.out.println("사용자 메시지: 죄송합니다. 알 수 없는 문제가 발생했습니다.");
    System.out.println("==개발자용 디버깅 메시지==");
    e.printStackTrace(System.out);

    // 필요하면 예외 별로 별도의 처리 가능
    if (e instanceof SendExceptionV4 sendException) {
      System.out.println("[전송 오류] 전송 데이터: " + sendException.getSendData());
    }
  }
}
```

- 우선 `RuntimeException`을 상속 받아 [[체크 예외와 언체크 예외#언체크 예외|언체크 예외]]로 만든다.
- 언체크 예외는 `catch` 하지 않으면 자동으로 `throws`를 하기 때문에 따로 작성하지 않는다.
- 최상위 호출부에서 `try-catch` 구문을 통해 예외 계층 중 `Exception` 타입을 캐치한다.
  - `Exception`의 하위 예외들은 모두 함께 잡힌다.
- 최상위 호출부의 클래스에 공통 예외 처리 함수를 따로 만들어 처리한다.
- 예외도 객체이므로 `instanceof`를 사용하여 별도로 예외 객체의 타입을 확인해서 추가 처리를 할 수 있다.
- 최대한 빨리 문제를 찾고 디버깅 할 수 있도록 에러 로그를 남겨두어야 한다.

## try-with-resources

어플리케이션에서 외부 자원을 사용하는 경우 반드시 외부 자원과의 연결을 해제해야 한다. 따라서 반드시 `finally` 키워드를 사용해야 한다.

`try`에서 외부 자원을 사용하고, `try`가 끝나면 외부 자원을 반납하는 패턴이 반복되면서 자바에서는 `Try with resources`라는 편의 기능을 자바 7에서 도입했다.

```java title="AutoCloseable.java"
public interface AutoCloseable {
	void close() throws Exception;
}
```

이 기능을 사용하려면 위의 `AutoCloseable` 인터페이스를 구현해야 한다. 이 인터페이스를 구현하면 `Try with resources`를 사용할 때 `try`가 끝나는 시점에 자동으로 `close()`가 호출된다.

그리고 다음과 같이 `Try with resources`를 사용하면 된다.

```java title="Try with resources 사용 예시"
try (Resource resource = new Resource()) {
	...
}
```

위의 예시에서 `Resource` 클래스는 `AutoCloseable` 인터페이스를 구현해야 한다.

**실제 구현 예시**

```java title="NetworkClientV5.java"
public class NetworkClientV5 implements AutoCloseable {
  private final String address;
  public boolean connectError;
  public boolean sendError;

  public NetworkClientV5(String address) {
    this.address = address;
  }

  public void connect() {
    if (connectError) {
      throw new ConnectExceptionV4(address, address + " 서버 연결 실패");
    }

    System.out.println(address + " 서버 연결 성공");
  }

  public void send(String data) {
    if (sendError) {
      throw new SendExceptionV4(data, address + " 서버에 데이터 전송 실패: " + data);
    }

    System.out.println(address + " 서버에 데이터 전송: " + data);
  }

  public void disconnect() {
    System.out.println(address + " 서버 연결 해제");
  }

  public void initError(String data) {
    if (data.contains("error1")) {
      connectError = true;
    } else if (data.contains("error2")) {
      sendError = true;
    }
  }

  @Override
  public void close() {
    System.out.println("NetworkClientV5.close");
    disconnect();
  }
}
```

아래는 `NetworkClientV5`를 사용하는 `NetworkServiceV5` 클래스다.

```java title="NetworkServiceV5.java"

public class NetworkServiceV5 {
  public void sendMessage(String data) {
    String address = "http://example.com";

    try (NetworkClientV5 client = new NetworkClientV5(address)){
      client.initError(data);
      client.connect();
      client.send(data);
    } catch (Exception e) {
      System.out.println("[예외 확인]: " + e.getMessage());
      throw e;
    }
  }
}
```

- Try with resources 구문은 `try` 괄호 안에 사용할 자원을 명시한다.
- 이 자원은 `try` 블럭이 끝나면 자동으로 `Autocloseable.close()`를 호출해서 자원을 해제한다.
- 참고로 여기서 `catch` 블럭 없이 `try` 블럭만 있어도 `close()`는 호출된다.

> [!note] Try with resources 장점
>
> **리소스 누수 방지**: 모든 리소스가 제대로 닫히도록 보장한다. 실수로 `finally` 블록을 적지 않거나 `finally` 블록 안에서 자원 해제 코드를 누락하는 문제들을 예방할 수 있다.
> **코드 간결성 및 가독성 향상**: 명시적인 `close()` 호출이 필요 없어 코드가 더 간결하고 읽기 쉬워진다.
>
> **스코프 범위 한정**: 예를 들어 리소스로 사용되는 `client` 변수의 스코프가 `try` 블록 안으로 한정된다. 따라서 코드 유지보수가 더 쉬워진다.
>
> **조금 더 빠른 자원 해제**: 기존에는 `try` > `catch` > `finally`로 `catch` 절 이후에 자원을 반납했다. `Try with resources` 구문은 `try` 블럭이 끝나면 즉시 `close()`를 호출한다.

---

References: 김영한의 실전 자바 - 중급 1편

Links to this page: [[체크 예외와 언체크 예외]]
