---
title:
tags:
  - java
  - programming
  - exception
publish: true
date: 2024-10-09
---

## 예외 계층화

![[예외-계층화1.png]]
예외를 단순히 오류 코드로 분류하는 것이 아니라, 예외를 계층화해서 다양하게 만들면 더 세밀하게 예외를 처리 할 수 있다.

**예외 계층화 예시**

- `NetworkClientExceptionV3`: `NetworkClient`에서 발생하는 모든 예외의 부모 객체
- `ConnectExceptionV3`: 연결 실패시 발생하는 예외이다. 내부에 연결을 시도한 `address`를 보관한다.
- `SendExceptionV3`: 전송 실패시 발생하는 예외이다. 내부에 전송을 시도한 데이터인 `sendData`를 보관한다.

이렇게 예외를 계층화하면 다음과 같은 장점이 있다.

- 자바에서 예외는 객체이다. 즉, [[resources/프로그래밍/강의/김영한의 자바/기본/다형성|다형성]]을 이용할 수 있다. 따라서 부모 예외를 잡거나 던지면 자식 예외도 함께 잡거나 던질 수 있다.
- 특정 예외를 잡아서 처리하고 싶으면 `ConnectExceptionV3`, `SendExceptionV3`와 같은 하위 예외를 잡아서 처리하면 된다.

## 예외 계층화 활용 1

```java title="예외 계층화 예제 1"
public void sendMessage(String data) {
  String address = "http://example.com";

  NetworkClientV3 client = new NetworkClientV3(address);
  client.initError(data);

  try {
    client.connect();
    client.send(data);
  } catch (SendExceptionV3 e) {
    System.out.println("[전송 오류] 주소: " + e.getSendData() + ", 메시지: " + e.getMessage());
  } catch (ConnectExceptionV3 e) {
    System.out.println("[연결 오류] 주소: " + e.getAddress() + ", 메시지: " + e.getMessage());
  } finally {
    client.disconnect();
  }
}
```

- `try`절 내부에는 정상 흐름이 들어있다.
- `catch`절엔 잡고자 하는 예외인 `SendExceptionV3`와 `ConnectExceptionV3`가 명시되어 있다. 서로 다른 기능을 제공하므로 두 개의 절로 나누었다.
- 마지막으로 `finally` 키워드를 사용하여 잡고자 하는 예외가 처리되지 않을 때에도 무조건 리소스 반환을 먼저 하도록 했다.

## 예외 계층화 활용 2

만약 `NetworkClientV3`에서 수 많은 예외를 발생한다고 가정해보면, 모든 예외를 [[예외 계층화와 활용#예외 계층화 활용 1|예외 계층화 예제 1]]의 코드처럼 하나 하나 `catch` 하여 처리하기 번거로울 것이다.

```java title="예외 계층화 예제 2"
public void sendMessage(String data) {
  String address = "http://example.com";

  NetworkClientV3 client = new NetworkClientV3(address);
  client.initError(data);

  try {
    client.connect();
    client.send(data);
  } catch (ConnectExceptionV3 e) {
    System.out.println("[연결 오류] 주소: " + e.getAddress() + ", 메시지: " + e.getMessage());
  } catch (NetworkClientExceptionV3 e) {
    System.out.println("[네트워크 오류] 메시지: " + e.getMessage());
  } catch (Exception e) {
    System.out.println("[알 수 없는 오류] 메시지: " + e.getMessage());
  } finally {
    client.disconnect();
  }
}
```

1. `ConnectExceptionV3`가 발생하면 최상단에 위치한 `catch`절에서 처리된다.
2. `ConnectExceptionV3` 외에 `NetworkClientExceptionV3`와 그 하위 예외 객체들은 모두 2번째 `catch`절에서 처리된다.
3. 이 외에 `Exception`은 모두 마지막 `catch`절에서 처리된다.

> [!warning]
> 예외가 발생했을 때, `catch`를 순서대로 실행하므로 더 디테일한 자식을 먼저 잡아야 한다.

## 여러 예외를 한번에 잡는 기능

다음과 같이 `|`를 사용해서 여러 예외를 한번에 잡을 수 있다. 참고로 이 경우 각 예외들의 공통 부모의 기능만 사용할 수 있다. 여기서는 `NetworkClientExceptionV3`의 기능만 사용할 수 있다.

```java title="예외 계층화 예제 3"
try {

} catch (ConnectExceptionV3 | SendExceptionV3 e) {
	System.out.println("[연결 또는 전송 오류] 메시지" + e.getMessage());
} finally {
	...
}
```

---

References: 김영한의 실전 자바 - 중급 1편

Links to this page: [[예외 계층]]
