---
title: 
tags:
  - java
  - programming
  - transaction
  - exception
  - spring
publish: true
date: 2024-12-27 00:00
---

## 예외와 트랜잭션 커밋, 롤백 - 기본

예외가 발생했는데, 내부에서 예외를 처리하지 못하고 트랜잭션 범위 밖(`@Transactional이 적용된 AOP`)으로 예외를 던지면 어떻게 될까?

![[transaction-exception-1.png]]

예외 발생 시 스프링 트랜잭션 AOP는 예외의 종류에 따라 트랜잭션을 커밋하거나 롤백한다.

- 언체크 예외인 `RuntimeException`, `Error`와 그 하위 예외가 발생하면 트랜잭션을 롤백한다.
- 체크 예외인 `Exception`과 그 하위 예외가 발생하면 트랜잭션을 커밋한다.

먼저 예제 코드를 작성하기 전에 트랜잭션의 작동을 로그로 확인하기 위해 다음 설정을 추가한다.

```properties title="application.properties"
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
#JPA log
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.org.hibernate.resource.transaction=DEBUG
```

```java
@SpringBootTest
public class RollbackTest {

    @Autowired
    RollbackService service;

    @Test
    void runtimeException() {
        Assertions.assertThatThrownBy(() -> service.runtimeException())
                .isInstanceOf(RuntimeException.class);
    }

    @Test
    void checkedException() {
        Assertions.assertThatThrownBy(() -> service.checkedException())
                .isInstanceOf(MyException.class);
    }

    @Test
    void rollbackFor() {
        Assertions.assertThatThrownBy(() -> service.rollbackFor())
                .isInstanceOf(MyException.class);
    }

    @TestConfiguration
    static class RollbackTestConfig {
        @Bean
        RollbackService rollbackService() {
            return new RollbackService();
        }
    }


    @Slf4j
    static class RollbackService {
        // 런타임 예외 발생 -> 롤백
        @Transactional
        public void runtimeException() {
            log.info("call runtimeException");
            throw new RuntimeException();
        }

        // 체크 예외 발생 -> 커밋
        @Transactional
        public void checkedException() throws Exception {
            log.info("call checkedException");
            throw new MyException();
        }

        // 체크 예외 발생 -> rollbackFor -> 롤백
        @Transactional(rollbackFor = MyException.class)
        public void rollbackFor() throws Exception {
            log.info("call rollbackFor");
            throw new MyException();
        }
    }

    static class MyException extends Exception {
    }
}
```

테스트를 하나씩 실행해보면 앞서 학습한 대로, 다음과 같이 동작한다.

- `runtimeException()`: 롤백
- `checkedException()`: 커밋
- `rollbackFor()`: 롤백

## 예외와 트랜잭션 커밋, 롤백 - 활용

스프링은 도대체 왜 체크 예외는 커밋하고, 언체크 예외는 롤백할까? 스프링은 기본적으로 **체크 예외는 비즈니스 의미가 있을 때 사용**하고, **런타임 예외는 복구 불가능한 예외**로 가정한다. 참고로 꼭 이런 정책을 따를 필요는 없다.

그런데 비즈니스 의미가 있는 **비즈니스 예외**가 도대체 무슨 뜻일까? 비즈니스 예외를 예제로 알아본다.

**비즈니스 요구사항**

주문 시스템을 개발하는데, 상황에 따라 다음과 같이 조치한다.

- **정상**: 주문시 결제를 성공하면 주문 데이터를 저장하고 결제 상태를 완료로 처리한다.
- **시스템 예외**: 주문시 내부에 복구 불가능한 예외가 발생하면 전체 데이터를 롤백한다.
- **비즈니스 예외**: 주문시 결제 잔고가 부족하면 주문 데이터를 저장하고, 결제 상태를 대기로 처리한다.
  - 이 경우 고객에게 잔고 부족을 알리고 별도의 계좌로 입금하도록 한다.

이 때 결제 잔고가 부족하면 `NotEnoughMoneyException`이라는 체크 예외가 발생한다고 가정한다. 이 예외는 시스템에 문제가 있어서 발생하는 시스템 예외가 아니다. 시스템은 정상적으로 동작했지만 비즈니스 상황에서 문제가 되기 때문에 발생한 예외이다.

더 자세히 설명하면, 고객의 잔고가 부족한 것은 시스템에 문제가 있는 것이 아니다. 오히려 시스템은 정상 동작한 것이고 비즈니스 상황이 예외인 것이다. 이런 예외를 비즈니스 예외라 한다. 그리고 비즈니스 예외는 매우 중요하고 반드시 처리해야 하는 경우가 많으므로 체크 예외를 고려할 수 있다.

> 실무에서 개발을 할 때도, 항상 예외를 시스템 예외와 비즈니스 예외를 구분해서 생각해야한다.

이제 예제를 간단히 구현해본다.

```java
public class NotEnoughMoneyException extends Exception {
    public NotEnoughMoneyException(String message) {
        super(message);
    }
}

public interface OrderRepository extends JpaRepository<Order, Long> {
}

@Entity
@Table(name = "orders")
@Getter
@Setter
public class Order {
    @Id
    @GeneratedValue    private Long id;

    private String username; // 정상, 예외, 잔고 부족
    private String payStatus; // 대기, 완료
}
```

```java
@Service
@Slf4j
@RequiredArgsConstructor
public class OrderService {
    private final OrderRepository orderRepository;

    @Transactional
	public void order(Order order) throws NotEnoughMoneyException {
	    log.info("order 호출");
	    orderRepository.save(order);

	    log.info("결제 프로세스 진입");
	    if (order.getUsername().equals("예외")) {
	        log.info("시스템 예외 발생");
	        throw new RuntimeException("시스템 예외");
	    } else if (order.getUsername().equals("잔고 부족")) {
	        log.info("비즈니스 예외 발생");
	        order.setPayStatus("대기");
	        throw new NotEnoughMoneyException("잔고가 부족합니다.");
	    } else {
	        log.info("정상 승인");
	        order.setPayStatus("완료");
	    }
	    log.info("결제 프로세스 완료");

	}
}
```

- 정상: `payStatus`를 완료로 처리하고 정상 처리된다.
- 시스템 예외: `RuntimeException`이 발생한다.
- 잔고 부족 비즈니스 예외:
  - `payStatus`를 대기로 처리한다.
  - `NotEnoughMoneyException` 체크 예외가 발생한다.
  - 잔고 부족은 `payStatus`를 대기 상태로 두고, 체크 예외가 발생하지만 `order` 데이터는 커밋되기를 기대한다.

이제 의도한 대로 작동하는지 테스트 코드로 검증해본다.

```java
@SpringBootTest
@Slf4j
class OrderServiceTest {
    @Autowired
    OrderService orderService;
    @Autowired
    OrderRepository orderRepository;

    @Test
    void complete() throws NotEnoughMoneyException {
        // GIVEN
        Order order = new Order();
        order.setUsername("정상");

        // WHEN
        orderService.order(order);

        // THEN
        Order findOrder = orderRepository.findById(order.getId()).get();
        Assertions.assertThat(findOrder.getPayStatus()).isEqualTo("완료");
    }

    @Test
    void runtimeException() throws NotEnoughMoneyException {
        // GIVEN
        Order order = new Order();
        order.setUsername("예외");

        // WHEN
        Assertions.assertThatThrownBy(() -> orderService.order(order))
                .isInstanceOf(RuntimeException.class);

        // THEN
        Optional<Order> findOrder = orderRepository.findById(order.getId());
        Assertions.assertThat(findOrder).isEmpty();
    }

    @Test
    void bizException() {
        // GIVEN
        Order order = new Order();
        order.setUsername("잔고 부족");

        // WHEN
        try {
            orderService.order(order);
        } catch (NotEnoughMoneyException e) {
            log.info("고객에게 잔고 부족을 알리고 별도의 계좌로 입금하도록 안내");
        }

        // THEN
        Order findOrder = orderRepository.findById(order.getId()).get();
        Assertions.assertThat(findOrder.getPayStatus()).isEqualTo("대기");
    }
}
```

테스트 케이스를 모두 실행해보면 의도한 대로 정상적으로 작동한다.

#### 정리

`NotEnoughMoneyException`은 시스템에 문제가 발생한 것이 아니라, 비즈니스 문제 상황을 예외를 통해 알려준다. 마치 예외가 반환 값처럼 사용된다. 따라서 이 경우에는 트랜잭션을 커밋하는 것이 맞다. 이
경우 롤백하면 생성한 `Order` 자체가 사라진다. 그러면 고객에게 잔고 부족을 알리고 별도의 계좌로 입금하도록 안내해도 주문(`Order`) 자체가 사라지기 때문에 문제가 된다.

그런데 비즈니스 상황에 따라 체크 예외의 경우에도 트랜잭션을 커밋하지 않고, 롤백하고 싶을 수가 있다. 이때는 `@Transactional`의 `rollbackFor` 옵션을 사용하면 된다.

> 중요한 것은 이 예외가 비즈니스 예외인지, 시스템 예외인지 구분하고 정의하는 것이다. 어떻게 구현할 지는 개발자의 선택이다.

---

References: 김영한의 스프링 DB 2편

Links to this page:
